In [164]:
import os
import urllib.request


if not os.path.exists("the-verdict.txt"):
    url = "https://raw.githubusercontent.com/rasbt/LLMs-from-scratch/refs/heads/main/ch02/01_main-chapter-code/the-verdict.txt"
    file_path = "the-verdict.txt"
    urllib.request.urlretrieve(url, file_path)
    print("Fiel Downloaded")

In [165]:
with open("the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

In [166]:
print(raw_text)

I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no great surprise to me to hear that, in the height of his glory, he had dropped his painting, married a rich widow, and established himself in a villa on the Riviera. (Though I rather thought it would have been Rome or Florence.)

"The height of his glory"--that was what the women called it. I can hear Mrs. Gideon Thwing--his last Chicago sitter--deploring his unaccountable abdication. "Of course it's going to send the value of my picture 'way up; but I don't think of that, Mr. Rickham--the loss to Arrt is all I think of." The word, on Mrs. Thwing's lips, multiplied its _rs_ as though they were reflected in an endless vista of mirrors. And it was not only the Mrs. Thwings who mourned. Had not the exquisite Hermia Croft, at the last Grafton Gallery show, stopped me before Gisburn's "Moon-dancers" to say, with tears in her eyes: "We shall not look upon its like again"?

Well!--even through th

In [167]:
len(raw_text)

20479

In [168]:
import re
'''Tokenize the text into words, space and punctuation'''
text = "Hello, World! This is a test. Let's see how it works."
result = re.split(r"([,.?!]|\s)", text)
print(result)


['Hello', ',', '', ' ', 'World', '!', '', ' ', 'This', ' ', 'is', ' ', 'a', ' ', 'test', '.', '', ' ', "Let's", ' ', 'see', ' ', 'how', ' ', 'it', ' ', 'works', '.', '']


In [169]:
# use strip() to remove whitespace characters
result = [token for token in result if token.strip()]
print(result)

['Hello', ',', 'World', '!', 'This', 'is', 'a', 'test', '.', "Let's", 'see', 'how', 'it', 'works', '.']


In [170]:
# text = "Hello, World! Is this-- a test?"

result = re.split(r'([,.:;?_!"()\']|--|\s)', raw_text)
result = [item.strip() for item in result if item.strip()]
print(result)
preprocessed = result

['I', 'HAD', 'always', 'thought', 'Jack', 'Gisburn', 'rather', 'a', 'cheap', 'genius', '--', 'though', 'a', 'good', 'fellow', 'enough', '--', 'so', 'it', 'was', 'no', 'great', 'surprise', 'to', 'me', 'to', 'hear', 'that', ',', 'in', 'the', 'height', 'of', 'his', 'glory', ',', 'he', 'had', 'dropped', 'his', 'painting', ',', 'married', 'a', 'rich', 'widow', ',', 'and', 'established', 'himself', 'in', 'a', 'villa', 'on', 'the', 'Riviera', '.', '(', 'Though', 'I', 'rather', 'thought', 'it', 'would', 'have', 'been', 'Rome', 'or', 'Florence', '.', ')', '"', 'The', 'height', 'of', 'his', 'glory', '"', '--', 'that', 'was', 'what', 'the', 'women', 'called', 'it', '.', 'I', 'can', 'hear', 'Mrs', '.', 'Gideon', 'Thwing', '--', 'his', 'last', 'Chicago', 'sitter', '--', 'deploring', 'his', 'unaccountable', 'abdication', '.', '"', 'Of', 'course', 'it', "'", 's', 'going', 'to', 'send', 'the', 'value', 'of', 'my', 'picture', "'", 'way', 'up', ';', 'but', 'I', 'don', "'", 't', 'think', 'of', 'that', ',

In [171]:
len(preprocessed)

4690

## 2.3 Converting tokens to token IDs

In [172]:
# From processed text to vocabulary
all_words = sorted(set(preprocessed))
vocab_size = len(all_words)
print(len(preprocessed))
print(vocab_size)

vocab = {token: id for id, token in enumerate(all_words) }
print(all_words)
print(vocab)

4690
1130
['!', '"', "'", '(', ')', ',', '--', '.', ':', ';', '?', 'A', 'Ah', 'Among', 'And', 'Are', 'Arrt', 'As', 'At', 'Be', 'Begin', 'Burlington', 'But', 'By', 'Carlo', 'Chicago', 'Claude', 'Come', 'Croft', 'Destroyed', 'Devonshire', 'Don', 'Dubarry', 'Emperors', 'Florence', 'For', 'Gallery', 'Gideon', 'Gisburn', 'Gisburns', 'Grafton', 'Greek', 'Grindle', 'Grindles', 'HAD', 'Had', 'Hang', 'Has', 'He', 'Her', 'Hermia', 'His', 'How', 'I', 'If', 'In', 'It', 'Jack', 'Jove', 'Just', 'Lord', 'Made', 'Miss', 'Money', 'Monte', 'Moon-dancers', 'Mr', 'Mrs', 'My', 'Never', 'No', 'Now', 'Nutley', 'Of', 'Oh', 'On', 'Once', 'Only', 'Or', 'Perhaps', 'Poor', 'Professional', 'Renaissance', 'Rickham', 'Riviera', 'Rome', 'Russian', 'Sevres', 'She', 'Stroud', 'Strouds', 'Suddenly', 'That', 'The', 'Then', 'There', 'They', 'This', 'Those', 'Though', 'Thwing', 'Thwings', 'To', 'Usually', 'Venetian', 'Victor', 'Was', 'We', 'Well', 'What', 'When', 'Why', 'Yes', 'You', '_', 'a', 'abdication', 'able', 'about'

In [173]:
class SimpleTokenizerV1:
    def __init__(self, vocab):
        self.str_to_int = vocab
        self.int_to_str = {id:token for token, id in vocab.items()}

    def encode(self, text):
        result = re.split(r'([,.:;?_!"()\']|--|\s)', text)
        result = [item.strip() for item in result if item.strip()]
        tokenids = [self.str_to_int[token] for token in result]
        return tokenids

    def decode(self, token_ids):
        tokens = [self.int_to_str[id] for id in token_ids]
        text = " ".join(tokens)
        # 去除标点符号token前面的空格
        text = re.sub(r'\s+([,.?!"()\'])', r'\1', text)
        return text

In [174]:
text = '''"It's the last he painted, you know," Mrs. Gisburn said with pardonable pride.'''

tkzer = SimpleTokenizerV1(vocab)
print(tkzer.str_to_int)
print(tkzer.int_to_str)

token_ids = tkzer.encode(text)
print(token_ids)

text = tkzer.decode(token_ids)
print(text)

{'!': 0, '"': 1, "'": 2, '(': 3, ')': 4, ',': 5, '--': 6, '.': 7, ':': 8, ';': 9, '?': 10, 'A': 11, 'Ah': 12, 'Among': 13, 'And': 14, 'Are': 15, 'Arrt': 16, 'As': 17, 'At': 18, 'Be': 19, 'Begin': 20, 'Burlington': 21, 'But': 22, 'By': 23, 'Carlo': 24, 'Chicago': 25, 'Claude': 26, 'Come': 27, 'Croft': 28, 'Destroyed': 29, 'Devonshire': 30, 'Don': 31, 'Dubarry': 32, 'Emperors': 33, 'Florence': 34, 'For': 35, 'Gallery': 36, 'Gideon': 37, 'Gisburn': 38, 'Gisburns': 39, 'Grafton': 40, 'Greek': 41, 'Grindle': 42, 'Grindles': 43, 'HAD': 44, 'Had': 45, 'Hang': 46, 'Has': 47, 'He': 48, 'Her': 49, 'Hermia': 50, 'His': 51, 'How': 52, 'I': 53, 'If': 54, 'In': 55, 'It': 56, 'Jack': 57, 'Jove': 58, 'Just': 59, 'Lord': 60, 'Made': 61, 'Miss': 62, 'Money': 63, 'Monte': 64, 'Moon-dancers': 65, 'Mr': 66, 'Mrs': 67, 'My': 68, 'Never': 69, 'No': 70, 'Now': 71, 'Nutley': 72, 'Of': 73, 'Oh': 74, 'On': 75, 'Once': 76, 'Only': 77, 'Or': 78, 'Perhaps': 79, 'Poor': 80, 'Professional': 81, 'Renaissance': 82, 'Ri

## 2.4 Adding special context tokens

In [175]:
text = "Hello world"
print(tkzer.decode(tkzer.encode(text)))

KeyError: 'Hello'

In [176]:
all_words = sorted(list(set(preprocessed)))
all_words.extend(["<|endoftext|>", "<|unk|>"])
vocab_size = len(all_words)
print(vocab_size)


1132


In [177]:
vocab = {token:id for id, token in enumerate(all_words)}

In [178]:
for item in list(vocab.items())[-5:]:
    print(item)

('younger', 1127)
('your', 1128)
('yourself', 1129)
('<|endoftext|>', 1130)
('<|unk|>', 1131)


In [179]:
class SimpleTokenizerV2:
    def __init__(self, vocab):
        self.str_to_int = vocab
        self.int_to_str = {id:token for token, id in vocab.items()}

    def encode(self, text):
        result = re.split(r'([,.:;?_!"()\']|--|\s)', text)
        result = [item.strip() for item in result if item.strip()]
        result = [
            item if item in self.str_to_int
            else '<|unk|>' for item in result
        ]
        
        tokenids = [self.str_to_int[token] for token in result]
        return tokenids

    def decode(self, token_ids):
        tokens = [self.int_to_str[id] for id in token_ids]
        text = " ".join(tokens)
        # 去除标点符号token前面的空格
        text = re.sub(r'\s+([,.?!"()\'])', r'\1', text)
        return text

In [180]:
tkzer = SimpleTokenizerV2(vocab)
text = "Hello, do you like tea? is this-- a test?"
ids = tkzer.encode(text)
print(ids)

print(tkzer.decode(ids))

[1131, 5, 355, 1126, 628, 975, 10, 584, 999, 6, 115, 1131, 10]
<|unk|>, do you like tea? is this -- a <|unk|>?


## 2.5 Byte pair encoding

In [181]:
import tiktoken

In [182]:
tiktoken.__version__

'0.12.0'

In [183]:
tokenizer = tiktoken.get_encoding("gpt2")


In [184]:
tokenizer.encode("Hello world")

[15496, 995]

In [185]:
tokenizer.decode(tokenizer.encode("Hello world"))

'Hello world'

In [186]:
text = (
    "Hello, do you like tea? <|endoftext|> In jhbito...ie fjeioal nihao caonima the sunlit terraces"
     "of someunknownPlace."
)

code = tokenizer.encode(text, allowed_special={"<|endoftext|>"})
print(code)

[15496, 11, 466, 345, 588, 8887, 30, 220, 50256, 554, 474, 71, 2545, 78, 986, 494, 277, 18015, 952, 282, 37628, 23778, 1275, 261, 8083, 262, 4252, 18250, 8812, 2114, 1659, 617, 34680, 27271, 13]


In [187]:
tokenizer.decode(code)

'Hello, do you like tea? <|endoftext|> In jhbito...ie fjeioal nihao caonima the sunlit terracesof someunknownPlace.'

## 2.6 Data sampling with a sliding window

In [188]:
with open("the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

enc_text = tokenizer.encode(raw_text)
print(len(enc_text))

5145


In [189]:
enc_sample = enc_text[50:] #为什么去掉前50个
print(enc_sample)
print(tokenizer.decode(enc_sample[:10]))

[290, 4920, 2241, 287, 257, 4489, 64, 319, 262, 34686, 41976, 13, 357, 10915, 314, 2138, 1807, 340, 561, 423, 587, 10598, 393, 28537, 2014, 198, 198, 1, 464, 6001, 286, 465, 13476, 1, 438, 5562, 373, 644, 262, 1466, 1444, 340, 13, 314, 460, 3285, 9074, 13, 46606, 536, 5469, 438, 14363, 938, 4842, 1650, 353, 438, 2934, 489, 3255, 465, 48422, 540, 450, 67, 3299, 13, 366, 5189, 1781, 340, 338, 1016, 284, 3758, 262, 1988, 286, 616, 4286, 705, 1014, 510, 26, 475, 314, 836, 470, 892, 286, 326, 11, 1770, 13, 8759, 2763, 438, 1169, 2994, 284, 943, 17034, 318, 477, 314, 892, 286, 526, 383, 1573, 11, 319, 9074, 13, 536, 5469, 338, 11914, 11, 33096, 663, 4808, 3808, 62, 355, 996, 484, 547, 12548, 287, 281, 13079, 410, 12523, 286, 22353, 13, 843, 340, 373, 407, 691, 262, 9074, 13, 536, 48819, 508, 25722, 276, 13, 11161, 407, 262, 40123, 18113, 544, 9325, 701, 11, 379, 262, 938, 402, 1617, 261, 12917, 905, 11, 5025, 502, 878, 402, 271, 10899, 338, 366, 31640, 12, 67, 20811, 1, 284, 910, 11, 351, 10

In [190]:
len(enc_sample)

5095

In [191]:
context_size = 4

x = enc_sample[:context_size]
y = enc_sample[1:context_size+1]

print(f"x: {x}")
print(f"y:      {y}")

x: [290, 4920, 2241, 287]
y:      [4920, 2241, 287, 257]


In [192]:
# Byte Pairing Encode方法每个token是子词，普通单词也可能被拆分为单独词语。正常现象
for t in enc_sample[:12]:
    print(tokenizer.decode([t]))

 and
 established
 himself
 in
 a
 vill
a
 on
 the
 Riv
iera
.


In [193]:
for i in range(len(enc_sample)-1):
    x = enc_sample[i:i+context_size]
    y = enc_sample[i+1:i+1+context_size]

    print(f"x: {tokenizer.decode(x)}")
    print(f"y:     {tokenizer.decode(y)}")
    print()

x:  and established himself in
y:      established himself in a

x:  established himself in a
y:      himself in a vill

x:  himself in a vill
y:      in a villa

x:  in a villa
y:      a villa on

x:  a villa on
y:      villa on the

x:  villa on the
y:     a on the Riv

x: a on the Riv
y:      on the Riviera

x:  on the Riviera
y:      the Riviera.

x:  the Riviera.
y:      Riviera. (

x:  Riviera. (
y:     iera. (Though

x: iera. (Though
y:     . (Though I

x: . (Though I
y:      (Though I rather

x:  (Though I rather
y:     Though I rather thought

x: Though I rather thought
y:      I rather thought it

x:  I rather thought it
y:      rather thought it would

x:  rather thought it would
y:      thought it would have

x:  thought it would have
y:      it would have been

x:  it would have been
y:      would have been Rome

x:  would have been Rome
y:      have been Rome or

x:  have been Rome or
y:      been Rome or Florence

x:  been Rome or Florence
y:      Rome or Florence.)

x: 

In [194]:
for i in range(1,context_size+1):
    context = enc_sample[:i]
    desired = enc_sample[i]

    print(f"{context}  ---> {desired}")

[290]  ---> 4920
[290, 4920]  ---> 2241
[290, 4920, 2241]  ---> 287
[290, 4920, 2241, 287]  ---> 257


In [195]:
import torch

torch.__version__

'2.10.0+cpu'

In [200]:
from torch.utils.data import Dataset, DataLoader

# 作用是整合tokenizer，记录当前总训练输入和总输入+输出
# max_length是最大窗口长度，stride是每次移动多少
class GPTDatasetV1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []

        token_ids = tokenizer.encode(txt, allowed_special={"<|endoftext|>"})

        for i in range(0, len(token_ids) - max_length, stride):
            input_chunk = token_ids[i:i+max_length]
            target_chunk = token_ids[i+1: i+max_length+1] # 1是每次加载多少作为target
            self.input_ids.append(torch.tensor(input_chunk)) 
            self.target_ids.append(torch.tensor(target_chunk))
            #print(self.input_ids)
            #print(self.target_ids)

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self,idx):
        return self.input_ids[idx], self.target_ids[idx]

In [231]:
# drop_last丢弃最后一组，可能不满batch_size；
def create_dataloader_v1(txt, batch_size=2, max_length=256,
                        stride=128, shuffle=True, drop_last=True,
                        num_workers=2):
                        
    tokenizer = tiktoken.get_encoding("gpt2")

    dataset = GPTDatasetV1(txt, tokenizer, max_length, stride)

    dataLoader = DataLoader(
                dataset,
                batch_size=batch_size,
                shuffle = shuffle,
                drop_last = drop_last,
                num_workers = num_workers
    )

    return dataLoader

In [232]:
with open("the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

In [233]:
dataloader = create_dataloader_v1(raw_text, batch_size=1, max_length=4, stride=1, shuffle=False,num_workers=0)

data_iter = iter(dataloader)
first_batch = next(data_iter)
print(first_batch)

[tensor([[  40,  367, 2885, 1464]]), tensor([[ 367, 2885, 1464, 1807]])]


In [234]:
first_batch = next(data_iter)
print(first_batch)

[tensor([[ 367, 2885, 1464, 1807]]), tensor([[2885, 1464, 1807, 3619]])]


In [235]:
#为了避免相邻两次overlap，可以调整stride=max_length
#为了提高效率，可以设置batch_size
dataloader = create_dataloader_v1(raw_text, batch_size=4, max_length=4, stride=4, shuffle=False)

data_iter = iter(dataloader)
inputs, outputs = next(data_iter)
print("Inputs:\n", inputs)
print("Outputs:\n", outputs)


Inputs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257]])
Outputs:
 tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922]])


## 2.7 Create token embeddings

Token embedding通常是LLM的一部分，这里为了连贯性和token放在一起

In [236]:
inputs_ids = torch.tensor([2, 3, 5, 1])

```class torch.nn.Embedding(num_embeddings, embedding_dim, padding_idx=None, max_norm=None, norm_type=2.0, scale_grad_by_freq=False, sparse=False, _weight=None, _freeze=False, device=None, dtype=None)```   [官网介绍](https://docs.pytorch.org/docs/stable/generated/torch.nn.Embedding.html)

一个简单的查找表，存储固定字典和大小的嵌入。

这个模块通常用于存储词嵌入，并通过索引检索它们。 模块的输入是一系列索引，输出是相应的词嵌入。

* num_embeddings (int) 嵌入词典的大小    
* embedding_dim (int) 每个嵌入向量的大小   
* ......

In other words, the embedding layer is essentially a lookup operation that retrieves rows from the embedding layer’s weight matrix via a token ID.

嵌入层本质上就是一个查找操作 (lookup operation)，它通过 token ID 从嵌入层的权重矩阵中检索出对应的行。

In [237]:
vocab_size = 6
output_dim = 3

torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [238]:
print(embedding_layer.weight.shape)

torch.Size([6, 3])


In [239]:
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [240]:
embedding_layer(torch.tensor([2]))

tensor([[ 1.2753, -0.2010, -0.1606]], grad_fn=<EmbeddingBackward0>)

In [241]:
embedding_layer(torch.tensor([3]))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)

In [242]:
embedding_layer(inputs_ids)

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)

In [243]:
print(inputs_ids)

tensor([2, 3, 5, 1])


## 2.8 Position embedding

| 问题 (Question) | 回答 (Answer) |
| :--- | :--- |
| **为什么要把文本转换成数字 ID (Token)？** | 计算机无法处理字符，只能运算数字。Tokenization 为每个词分配“身份证号”，将其转化为离散的整数索引。🔢 |
| **为什么有了 ID 还要转换成向量 (Embedding)？** | 整数 ID 本身不包含语义联系。Embedding 将 ID 映射到空间坐标，使得**语义相近**的词在空间中距离更近，捕捉词汇间的逻辑关联。📍 |
| **为什么维度一定要非常高（如 768 维），3 或 4 维不行吗？** | 人类语言极其复杂。一个词通常包含多种属性（如：苹果既是水果也是科技公司）。低维度空间无法同时满足多个语义维度的排列要求，会导致**语义冲突**或**歧义**。多维度提供了足够的“余地”来容纳复杂的词汇关系。🌌 |
|**为什么要用Position embedding**|因为模型看到的token是数学上的集合，没有顺序关系，它只计算token之间的相似度，不考虑第几个词/前后关系/顺序编号。把“位置”变成向量，加进 token embedding 里可以让模型强制考虑相对关系。考虑绝对举例->token之间的距离|


In [244]:
print(tokenizer.n_vocab)

50257


In [245]:
vocab_size = tokenizer.n_vocab
output_dim = 256

embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [ ]:
max_length = 4
dataloader = create_dataloader_v1(raw_text, batch_size=8,max_length=max_length, stride=4, shuffle=False)

data_iter = iter(dataloader)
inputs, outputs = next(data_iter) # 每一次的总输入和期望输出


In [250]:
print("Token IDs:\n", inputs)
print("\nInputs shape:\n", inputs.shape)

Token IDs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])

Inputs shape:
 torch.Size([8, 4])


In [251]:
token_embeddings = embedding_layer(inputs)
token_embeddings.shape
#print(token_embeddings[0,0])

torch.Size([8, 4, 256])

引入Position embedding, window内每个embedding分别加上0，1，...的pos_embedding。

Position Embedding 的作用是：

**把 Bag of Words 变回 Sentence**

没有 position：

> 苹果 吃 我

和

> 我 吃 苹果

完全等价。

In [263]:
torch.arange(max_length) #生成序数


tensor([0, 1, 2, 3])

In [264]:
context_lentgh = max_length
pos_token_embeddings = torch.nn.Embedding(context_lentgh, output_dim)


In [265]:
pos_token_embeddings.weight

Parameter containing:
tensor([[-0.8290,  0.0647,  0.1265,  ...,  0.3610,  1.0378,  0.7732],
        [-0.3407, -0.0392,  1.8435,  ...,  0.5663,  1.3551, -1.9100],
        [-1.0489, -0.4816, -0.8424,  ...,  0.9912, -0.6396,  1.3296],
        [ 0.2580,  0.3851,  0.0491,  ...,  1.3488, -1.6770, -0.4796]],
       requires_grad=True)

In [266]:
pos_embeddings = pos_token_embeddings(torch.arange(max_length))

In [270]:
print(token_embeddings.shape)
print(pos_embeddings.shape)


torch.Size([8, 4, 256])
torch.Size([4, 256])


In [271]:
token_embeddings[0] + pos_embeddings

tensor([[-0.3377,  1.1886,  1.5854,  ..., -0.0385, -0.8358,  0.6286],
        [ 0.1073,  0.2144,  1.5780,  ...,  1.0660,  0.1560, -3.0944],
        [-1.2996, -0.5362, -0.1737,  ...,  1.9530,  1.7341,  1.2767],
        [ 1.2037,  1.2509,  1.6682,  ...,  0.8944, -2.4230, -0.1313]],
       grad_fn=<AddBackward0>)

In [273]:
input_embeddings = token_embeddings + pos_embeddings
print(input_embeddings)

tensor([[[-0.3377,  1.1886,  1.5854,  ..., -0.0385, -0.8358,  0.6286],
         [ 0.1073,  0.2144,  1.5780,  ...,  1.0660,  0.1560, -3.0944],
         [-1.2996, -0.5362, -0.1737,  ...,  1.9530,  1.7341,  1.2767],
         [ 1.2037,  1.2509,  1.6682,  ...,  0.8944, -2.4230, -0.1313]],

        [[ 0.7170,  1.8016, -0.6582,  ...,  0.2606,  1.8962,  0.4311],
         [-2.2029, -0.2306,  1.4623,  ...,  1.6883,  1.0056, -1.3009],
         [ 0.9358, -1.1299, -0.9839,  ...,  0.6071, -1.5751,  2.7774],
         [ 1.2227,  1.6825, -1.5716,  ...,  2.4951, -0.0973, -0.0827]],

        [[-1.6003,  0.7219,  0.2928,  ..., -0.4433,  1.0919,  1.5158],
         [ 0.4638,  0.4655,  3.1357,  ...,  2.0311,  1.7648, -1.5894],
         [-0.9695, -2.2452, -0.2674,  ...,  3.1735,  1.1835,  0.9661],
         [ 0.6847,  0.3204,  0.6177,  ...,  0.8279, -0.3705,  0.3677]],

        ...,

        [[-2.4446,  1.0257, -2.5171,  ..., -0.6034,  2.1266,  2.4115],
         [-0.7392, -0.9627,  0.5272,  ..., -0.5919,  0.22

In [274]:
print(input_embeddings.shape)

torch.Size([8, 4, 256])
