Exercise 2.1 Byte pair encoding of unknown words

In [ ]:
import tiktoken

In [5]:
words = "Akwirw ier"
tknizer = tiktoken.get_encoding("gpt2")
tokens = tknizer.encode(words)
print(tokens)

[33901, 86, 343, 86, 220, 959]


In [11]:
for tk in tokens:
    print(f'"{tknizer.decode([tk])}"', end=", ")

"Ak", "w", "ir", "w", " ", "ier", 

In [12]:
decoded = tknizer.decode(tokens)
print(decoded)

Akwirw ier


Appendix A. Pytorch

In [2]:
import torch

# 当前安装的 PyTorch 库的版本
print(torch.__version__)
# 检查 CUDA 是否可用，即你的系统有 NVIDIA 的 GPU
print(torch.cuda.is_available())

2.10.0+cpu
False


A.2.1 标量、向量、矩阵和张量

In [7]:
import torch

In [14]:
tensors = [1,2,3,4,5]

tensor0d = torch.tensor(1)

tensor1d = torch.tensor([1,2,3])

tensor2d = torch.tensor([[1,2],
                        [3,4]
])

tensor3d = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(tensor3d)
print(tensor3d.dtype)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
torch.int64


In [15]:
floatvec = torch.tensor([1.0, 2.0, 3.0])
print(floatvec.dtype)

torch.float32


In [17]:
floatvec = tensor3d.to(torch.float32)
print(floatvec.dtype)

torch.float32


In [22]:
tensor2d = torch.tensor([[1,2,3], [4,5,6]])

print(tensor2d)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [23]:
print(tensor2d.shape)

torch.Size([2, 3])


In [24]:
print(tensor2d.reshape(3,2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [27]:
print(tensor2d.view(1,6)) #another way

tensor([[1, 2, 3, 4, 5, 6]])


In [29]:
print(tensor2d)
print(tensor2d.T)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [31]:
print(tensor2d.matmul(tensor2d.T))
print(tensor2d @ tensor2d.T)

tensor([[14, 32],
        [32, 77]])
tensor([[14, 32],
        [32, 77]])


2.7 创建 token 嵌入

In [1]:
import torch

In [2]:
input_ids = torch.tensor([2,3,5,1])

In [7]:
vocab_size = 6
output_dim = 3

In [11]:
torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In other words, the embedding layer is essentially a lookup operation that retrieves rows from the embedding layer’s weight matrix via a token ID.

嵌入层本质上就是一个查找操作 (lookup operation)，它通过 token ID 从嵌入层的权重矩阵中检索出对应的行。

In [12]:
print(embedding_layer(torch.tensor([2])))

tensor([[ 1.2753, -0.2010, -0.1606]], grad_fn=<EmbeddingBackward0>)


In [13]:
print(embedding_layer(torch.tensor([5])))

tensor([[-2.8400, -0.7849, -1.4096]], grad_fn=<EmbeddingBackward0>)


In [14]:
print(embedding_layer(torch.tensor([2, 3, 5, 1])))

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)
